-- Run this in Supabase SQL Editor.
create table if not exists public.addons (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text default '',
  edition text not null check (edition in ('bedrock','java')),
  file_url text not null,
  image_url text,
  downloads bigint not null default 0,
  created_at timestamptz not null default now()
);

alter table public.addons enable row level security;
create policy "public read addons" on public.addons for select using (true);
create policy "users insert own addons" on public.addons for insert with check (auth.uid() = user_id);
create policy "users update own addons" on public.addons for update using (auth.uid() = user_id);
create policy "users delete own addons" on public.addons for delete using (auth.uid() = user_id);

create or replace function public.increment_downloads(addon_id bigint)
returns void language sql security definer set search_path=public as $$
  update public.addons set downloads = downloads + 1 where id = addon_id;
$$;

-- Create Storage buckets named exactly:
-- addons       (public bucket)
-- addon-images (public bucket)
-- Then add Storage policies appropriate for authenticated uploads.
